In [5]:
import numpy as np

# Distance matrix representing distances between cities.
distance_matrix =[ 
    [0, 10, 30, 50],
    [10, 0, 40, 5],
    [30, 40, 0, 60],
    [50, 5, 60, 0],
]
# Defining the parameters
num_cities = len(distance_matrix)  # Number of cities in the problem.
num_ants = 20  # Number of ants used in the simulation.
num_iterations = 100  # Number of iterations to run the simulation."
decay = 0.5  # Rate at which pheromones decay.
alpha = 1  # Influence of pheromone levels on the decision-making.
beta = 2  # Influence of distance (visibility) on the decision-making.

# Initial pheromone levels are set very low.
pheromone_levels = np.ones((num_cities, num_cities)) * 1e-6
print(f"Initial pheromone level {pheromone_levels}")

# SECTION 1
def select_next_city(pheromone_levels, distance_matrix, current_city, visited):
    # Function to select the next city for the ant to visit.

    pheromones = pheromone_levels[current_city] ** alpha  # Pheromone levels raised to the power of alpha.
    visibility = np.zeros_like(pheromones)  # Array to store visibility (inverse of distance).

    for city in range(num_cities):
        if city not in visited and distance_matrix[current_city][city] != 0:
            # Calculate visibility for cities that haven't been visited yet.
            visibility[city] = (1.0 / distance_matrix[current_city][city]) ** beta
    
    # Calculate probabilities of moving to each city.
    probabilities = pheromones * visibility
    probabilities_sum = probabilities.sum()
    
    if probabilities_sum == 0:
        
        # If all probabilities are zero, select randomly among unvisited cities.
        return np.random.choice([city for city in range(num_cities) if city not in visited])
    
    probabilities /= probabilities_sum  # Normalize probabilities.
    return np.random.choice(num_cities, p=probabilities)  # Select next city based on probabilities.
    
# SECTION 2

def update_pheromones(pheromone_levels, routes, scores):
    # Function to update the pheromone levels on the paths.
    
    for i, route in enumerate(routes):
        for j in range(num_cities - 1):
            
            # Update pheromone levels based on the quality of the route (inverse of score).
            pheromone_levels[route[j], route[j+1]] += 1 / scores[i]
        pheromone_levels[route[-1], route[0]] += 1 / scores[i]
    
    # Apply decay to the pheromone levels.
    pheromone_levels *= (1 - decay)
    

# SECTION 3
# Variables to track the best route and its distance.
best_route = None    # null of java
best_distance = float('inf')  

for iteration in range(num_iterations):  
    # Main loop running for the specified number of iterations.
    routes = []
    distances = []
    
    for ant in range(num_ants):
        # Each ant starts at a random city.
        route = [np.random.randint(num_cities)]
        
        while len(route) < num_cities:
            current_city = route[-1]
            next_city = select_next_city(pheromone_levels, distance_matrix, current_city, route)
            route.append(next_city)
            
        routes.append(route)
        # Calculate the total distance of the route.
        route_distance = sum(distance_matrix[route[i]][route[i+1]] for i in range(-1, len(route)-1))
        distances.append(route_distance)
        
        if route_distance < best_distance:
            # Update best route if the current route is better.
            best_distance = route_distance
            best_route = route
    
    # Update pheromones based on the routes found in this iteration.
    update_pheromones(pheromone_levels, routes, distances)

# Print the best route and its distance.
print("Best route:", best_route)
print("Best route distance:", best_distance)


Initial pheromone level [[1.e-06 1.e-06 1.e-06 1.e-06]
 [1.e-06 1.e-06 1.e-06 1.e-06]
 [1.e-06 1.e-06 1.e-06 1.e-06]
 [1.e-06 1.e-06 1.e-06 1.e-06]]
Best route: [2, 0, 1, 3]
Best route distance: 105


In [20]:
import numpy as np

# Declaring distance matrix
distance_matrix = [
    [0,10,30,50],
    [10, 0, 40, 5],
    [30, 40, 0, 60],
    [50, 5, 60, 0],
]

# Defining the parameters
num_cities = len(distance_matrix)
num_ants  = 20
num_iterations = 100
decay = 0.5
alpha = 1
beta = 2

# Initial pheromone level 
pheromone_levels = np.ones((num_cities, num_cities))*1e-6

# Secion 1
def select_next_city(pheromone_levels, distance_matrix, current_city, visited):
    pheromones  = pheromone_levels[current_city]**alpha
    visibility = np.zeros_like(pheromones)  #Array to store the visibility inverse of distance

    # Calculating the visibility that haven't been selected yet
    for city in range(num_cities):
        if city not in visited and distance_matrix[current_city][city] != 0:
            visibility[city] = (1.0 / distance_matrix[current_city][city]) ** beta
        
     # CALCULATE THE PROBABILITIES OF MOVING TO EACH CITIES
    probabilities = pheromones*visibility
    probabilities_sum = probabilities.sum()

    if probabilities_sum == 0:
        return np.random.choice([city for city in range(num_cities) if city not in visited])

    probabilities /= probabilities_sum

    return np.random.choice(num_cities, p = probabilities)


# SECTION 2
def update_pheromones(pheromone_levels, routes, scores):
    for i , route in enumerate(routes):
        for j in range(num_cities -1):
            # Update the pheromone level based on the quality of the route i.e inverse  of the score
            pheromone_levels[route[j], route[j+1]] += 1/ scores[i]

        pheromone_levels[route[-1], route[0]] += 1/ scores[i]
    pheromone_levels *= (1 - decay)


# SECTION 3

# Variable to track the best route and distance
best_route = None
best_distance = float('inf')

for iteration in range(num_iterations):
    # Main loop for running specied number of times
    routes = []
    distances = []

    for ant in range(num_ants):
        # Each ant start at a random city
        route = [np.random.randint(num_cities)]

        while len(route) < num_cities:
            current_city = route[-1]
            next_city = select_next_city(pheromone_levels, distance_matrix,current_city, route)
            route.append(next_city)

        routes.append(route)

        # Calculate the total distance of the route
        route_distance = sum(distance_matrix[route[i]][route[i+1]] for i in range(-1, len(route)-1))
        distances.append(route_distance)
        if route_distance < best_distance:
            # Update the best route if current route is better
            best_distance = route_distance
            best_route = route

        # Update the pheromone based on the route found in this iteration
        update_pheromones(pheromone_levels, routes, distances)

print("Best route : ",best_route)
print("Optimal distance",best_distance)
            

Best route :  [3, 1, 0, 2]
Optimal distance 105
